doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '5.7'
    types:
      # guid type
      _uuid: 'App\Context\Account\Infrastructure\Persistence\Doctrine\Type\GuidType\DoctrineUuidType'
      registration__id: 'App\Context\Account\Infrastructure\Persistence\Doctrine\Type\GuidType\DoctrineRegistrationIdType'
      key_maker__id: 'App\Context\Account\Infrastructure\Persistence\Doctrine\Type\GuidType\DoctrineKeyMakerIdType'
      user__id: 'App\Context\Account\Infrastructure\Persistence\Doctrine\Type\GuidType\DoctrineUserIdType'
      role__id: 'App\Context\Account\Infrastructure\Persistence\Doctrine\Type\GuidType\DoctrineRoleIdType'
      permission__id: 'App\Context\Account\Infrastructure\Persistence\Doctrine\Type\GuidType\DoctrinePermissionIdType'
      credential__id: 'App\Context\Account\Infrastructure\Persistence\Doctrine\Type\GuidType\DoctrineCredentialIdType'
      credential_recovery__id: 'App\Context\Account\Infrastructure\Persistence\Doctrine\Type\GuidType\DoctrineCredentialRecoveryIdType'
      contact_data__id: 'App\Context\Account\Infrastructure\Persistence\Doctrine\Type\GuidType\DoctrineContactDataIdType'
      contact_data_change__id: 'App\Context\Account\Infrastructure\Persistence\Doctrine\Type\GuidType\DoctrineContactDataChangeIdType'
      outbox__id: 'App\Context\Account\Infrastructure\Persistence\Doctrine\Type\GuidType\DoctrineOutboxIdType'
      inbox__id: 'App\Context\Account\Infrastructure\Persistence\Doctrine\Type\GuidType\DoctrineInboxIdType'
      # data type
      email_address: 'App\Context\Account\Infrastructure\Persistence\Doctrine\Type\DataType\DoctrineEmailAddressType'
      phone_number: 'App\Context\Account\Infrastructure\Persistence\Doctrine\Type\DataType\DoctrinePhoneNumberType'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    mappings:
      dddcase_account_domain_model:
        type: xml
        dir: '%kernel.project_dir%/src/Context/Account/Infrastructure/Persistence/Doctrine/Config/Mapping/'
        prefix: 'App\Context\Account\Domain\Model'
