lexik_jwt_authentication:
  secret_key: '%env(resolve:JWT_SECRET_KEY)%'
  token_ttl: '%env(resolve:JWT_TOKEN_TTL)%' # interference token TTL in seconds
  user_identity_field: id
  user_id_claim: id
  encoder:
    # token encoder/decoder service - default implementation based on the lcobucci/jwt library
    service: lexik_jwt_authentication.encoder.lcobucci
    # encryption algorithm used by the encoder service
    signature_algorithm: HS256
  token_extractors:
    # look for a token as Authorization Header
    authorization_header:
      enabled: true
      prefix: Bearer
      name: Authorization
    cookie:
      enabled: false
    query_parameter:
      enabled: false
