twig:
  default_path: '%kernel.project_dir%/templates'
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  exception_controller: null
  globals:
    app:
      company: '%app.company%'
  paths:
    'src/Context/Account/Infrastructure/Templating/Twig/template': 'accountTemplate'

when@test:
  twig:
    strict_variables: true
