<?php

namespace App\Context\Account\Application\Security\AccessControl\Permission;

use MyCLabs\Enum\Enum;

/**
 * Class UserPermissionEnum
 * @package App\Context\Account\Application\Security\AccessControl\Permission
 */
final class UserPermissionEnum extends Enum
{
    public const PERMISSION__DDDCASE_ACCOUNT__USER_READ = 'PERMISSION__DDDCASE_ACCOUNT__USER_READ';
    // phpcs:ignore
    public const PERMISSION__DDDCASE_ACCOUNT__USER_READ_BY_CREDENTIAL = 'PERMISSION__DDDCASE_ACCOUNT__USER_READ_BY_CREDENTIAL';
    public const PERMISSION__DDDCASE_ACCOUNT__USERS_READ = 'PERMISSION__DDDCASE_ACCOUNT__USERS_READ';
    public const PERMISSION__DDDCASE_ACCOUNT__USER_UPDATE = 'PERMISSION__DDDCASE_ACCOUNT__USER_UPDATE';
    public const PERMISSION__DDDCASE_ACCOUNT__USER_ROLES_UPDATE = 'PERMISSION__DDDCASE_ACCOUNT__USER_ROLES_UPDATE';
    // phpcs:ignore
    public const PERMISSION__DDDCASE_ACCOUNT__USER_PERMISSIONS_READ = 'PERMISSION__DDDCASE_ACCOUNT__USER_PERMISSIONS_READ';
    // phpcs:ignore
    public const PERMISSION__DDDCASE_ACCOUNT__USER_CONTACT_DATA_READ = 'PERMISSION__DDDCASE_ACCOUNT__USER_CONTACT_DATA_READ';
    // phpcs:ignore
    public const PERMISSION__DDDCASE_ACCOUNT__CONTACT_DATA_CHANGE_CREATE = 'PERMISSION__DDDCASE_ACCOUNT__CONTACT_DATA_CHANGE_CREATE';
    // phpcs:ignore
    public const PERMISSION__DDDCASE_ACCOUNT__CONTACT_DATA_CHANGE_KEY_MAKER_READ = 'PERMISSION__DDDCASE_ACCOUNT__CONTACT_DATA_CHANGE_KEY_MAKER_READ';
    // phpcs:ignore
    public const PERMISSION__DDDCASE_ACCOUNT__CONTACT_DATA_CHANGE_SECRET_CODE_CREATE = 'PERMISSION__DDDCASE_ACCOUNT__CONTACT_DATA_CHANGE_SECRET_CODE_CREATE';
    // phpcs:ignore
    public const PERMISSION__DDDCASE_ACCOUNT__CONTACT_DATA_CHANGE_SIGN = 'PERMISSION__DDDCASE_ACCOUNT__CONTACT_DATA_CHANGE_SIGN';
    // phpcs:ignore
    public const PERMISSION__DDDCASE_ACCOUNT__USER_CREDENTIAL_READ = 'PERMISSION__DDDCASE_ACCOUNT__USER_CREDENTIAL_READ';
    // phpcs:ignore
    public const PERMISSION__DDDCASE_ACCOUNT__USER_CREDENTIAL_PASSWORD_UPDATE = 'PERMISSION__DDDCASE_ACCOUNT__USER_CREDENTIAL_PASSWORD_UPDATE';
    public const PERMISSION__DDDCASE_ACCOUNT__ROLE_READ = 'PERMISSION__DDDCASE_ACCOUNT__ROLE_READ';
    public const PERMISSION__DDDCASE_ACCOUNT__ROLES_READ = 'PERMISSION__DDDCASE_ACCOUNT__ROLES_READ';
}
